[package]
name = "naive-datetime-add"
version = "0.1.0"
edition = "2021"

[dependencies.jet_programmable_rust_binding]
git = "https://github.com/Byzanteam/jet-programmable-rust-binding"

[dependencies.time]
version = "0.3.9"
default-features = false
features = ["parsing", "macros", "formatting"]
