[package]
name = "table_row_field_value_to_cascader_field_value"
version = "0.1.0"
edition = "2021"

[dependencies.jet_programmable_rust_binding]
git = "https://github.com/Byzanteam/jet-programmable-rust-binding"
