[workspace]

members = [
    "next-day-of-week",
    "integer-sum",
    "departments-iterator",
    "get-naive-datetime-period-text",
    "naive-datetime-add",
    "get-naive-datetime-period-range"
]
