[package]
name = "networking-sample"
version = "0.1.0"
authors = ["ByzanTeam <dev@byzan.team>"]
edition = "2018"

[dependencies]
serde_json = "1.0.89"

[dependencies.jet_programmable_rust_binding]
git = "https://github.com/Byzanteam/jet-programmable-rust-binding"
features = ["networking"]
