[package]
name = "next-day-of-week"
version = "0.1.0"
authors = ["Phil Chen <06fahchen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
