name: Root wasms ci

on:
  pull_request:
    paths-ignore:
      - 'slp-api/**'
env:
  CARGO_TERM_COLOR: always

jobs:
  root-ci:
    uses: ./.github/workflows/rust-ci.yaml
    with:
      working-directory: ./

