name: Rust CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          default: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: cargo fmt --check
    - run: cargo clippy -- -D warnings
    - run: cargo build --verbose --target wasm32-unknown-unknown
    - run: cargo test --verbose
