name: SLP-API flows wasms ci

on:
  pull_request:
    paths:
      - 'slp-api/flows/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  slp-api-flows-ci:
    uses: ./.github/workflows/rust-ci.yaml
    with:
      working-directory: ./slp-api/flows/
