name: slp-api-ci

on:
  push:
    paths:
      - 'slp-api/flows/**'
  pull_request:
    paths:
      - 'slp-api/flows/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  check-slp-api-wasm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: slp-api/flows
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          default: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: cargo fmt --check
    - run: cargo clippy -- -D warnings
    - run: cargo build --verbose --target wasm32-unknown-unknown
    - run: cargo test --verbose
